query dices {
  dices {
    _id
    did,
    name,
    userId,
    actionIds,
    coverImg,
    createdAt
  }
}

query editDice($_id: String) {
  dice(_id: $_id) {
    _id
    did,
    name,
    userId,
    actionIds,
    coverImg,
    createdAt
  }
}